### PR TITLE
Updating domain link to klimerko.org

### PR DESCRIPTION
**Pull request by chedadsp**
Old domain vazduhgradjanima.rs changed to klimerko.org

### CODE REVIEW

**Comment by chedadsp** [comment]
Updated aliexpress link as well.

**Comment by epiller** [comment]
Thanks for contributing! I'm just wondering why you changed the PMS7003 link to another link of the same PMS7003?

**Comment by chedadsp** [comment]
Because original link doesn't work for me. It renders like obsolete.

**Comment by epiller** [comment]
I just tested the link and it's working properly, same as the new one. Weird. What do you mean by obsolete?

**Comment by chedadsp** [comment]
Hm. That ia really weird. What I get is:

We couldn't find your page

But we still have millions more shopping items for you to browse.
Keep shopping <https://www.aliexpress.com/>

**Comment by chedadsp** [comment]
I tried again but this time I deleted all the cookies. My shopping history tripped this somehow. I will reverte these changes.

**Pull request merged**
